create table if not exists public.contact_requests (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null,
  phone text not null,
  message text not null,
  status text not null default 'new',
  created_at timestamptz not null default now()
);

alter table public.contact_requests enable row level security;

drop policy if exists "Anyone can submit contact requests" on public.contact_requests;
create policy "Anyone can submit contact requests"
  on public.contact_requests
  for insert
  to anon, authenticated
  with check (true);
