create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  full_name text not null,
  rating smallint not null check (rating between 1 and 5),
  content text not null,
  created_at timestamptz not null default now(),
  constraint reviews_one_per_user unique (user_id)
);

alter table public.reviews enable row level security;

drop policy if exists "Anyone can read reviews" on public.reviews;
create policy "Anyone can read reviews"
  on public.reviews for select to anon, authenticated using (true);

drop policy if exists "Users can create their own review" on public.reviews;
create policy "Users can create their own review"
  on public.reviews for insert to authenticated
  with check (auth.uid() = user_id);
